knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        facebook_main:
            # this will be one of the supported types
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_facebook_check
            redirect_params: { }
            graph_api_version: v2.12
#        google_main:
#            type: google
#            client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
#            client_secret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'
#            redirect_route: connect_google_check
#            redirect_params: { }
        amazon_main:
            type: amazon
            client_id: '%env(OAUTH_AMAZON_CLIENT_ID)%'
            client_secret: '%env(OAUTH_AMAZON_CLIENT_SECRET)%'
            redirect_route: connect_amazon_check
            redirect_params: { }
